//PROBLEM 2: EVEN FIBONACCI NUMBERS 
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be : 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even - valued terms.
*/

#include <iostream>

int main()
{
	int firstNumber = 1;
	int secondNumber = 2;
	int total = 0;
	int evenTotal = 0;

	while (total < 4000000)
	{
		if (secondNumber % 2 == 0)
		{
			evenTotal += secondNumber;
		}

		total = firstNumber + secondNumber;
		firstNumber = secondNumber;
		secondNumber = total;		
	}

	std::cout << "ANSWER is " << evenTotal << std::endl;
	
	//CORRECT ANSWER: 4613732
	std::cin.get();
	return 0;
}
